name: Build Custom Bazzite

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Build image with ublue-os/recipe
        uses: ublue-os/recipe@v1
        with:
          recipe: recipe.yml
